### ISSUE TITLE
Add dispatching filters

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/executionorder#1]
Add dispatching filters

maybe a Foo dispatcher filter and how that effects the execution order.

**Comment by jadb** [comment]
Any pointers to how you see it being done?

**Comment by dereuromark** [comment]
Create a custom dispatching filter, load in it bootstrap and add the log calls.
Then update the RESULTS.md file.

**Comment by dereuromark** [comment]
We should add middleware here now instead. Closing.
